---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: app-test
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: app-wlp
        image: master_cfc_8500_default_app_latest
    spec:
      hostNetwork: false
      containers:
      - name: app-wlp
        image: mycluster:8500/default/app:latest
        imagePullPolicy: Always
        ports:
        - protocol: TCP
          containerPort: 9080
        - protocol: TCP
          containerPort: 9443
        resources:
          limits:
            cpu: 1
            memory: 1024Mi
      imagePullSecrets:
      - name: admin.registrykey
